destination: ./_site
encoding: 'utf-8'
exclude: [
    '.sass_cache',
    'bower_components',
    'node_modules',
    'src',
    'bower.json',
    'CHANGELOG.md',
    'Gruntfile.js',
    'package.json',
    'README.md'
]
include: ['.htaccess']
keep_files: ['assets']
permalink: /blog/:year/:month/:title
