# Locations
source: ./views
destination: ./_site

# Reading
encoding: 'utf-8'
exclude: [
    '.sass_cache',
    'bower_components',
    'node_modules',
    'src',
    'bower.json',
    'CHANGELOG.md',
    'Gruntfile.js',
    'package.json',
    'README.md'
]
include: ['.htaccess']
keep_files: ['assets']

# Outputting
permalink: /blog/:year/:month/:title/

# Conversion
kramdown:
    auto_ids: false
    hard_wrap: true
    input: GFM
    parse_block_html: true
    parse_span_html: true
